services:
  - type: web
    name: resto-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --worker-class eventlet -w 1"
    envVars:
      - key: FLASK_ENV
        value: production

